# Notebook Imports

In [1]:
import pandas as pd
import numpy as np

# Constants

In [2]:
TRAINING_DATA_FILE = r'SpamData\02_Training\train-data.txt'
TEST_DATA_FILE = r'SpamData\02_Training\test-data.txt'
VOCAB_SIZE = 2500


# Read and Load Features from .txt Files into NumPy Array

In [3]:
#the data came from sparse matrix
# 3 inputs for loadtxt -> relative path, delimiter (for boundry),dtype
# documentID,WordID,label(category),occurance -> all are int
sparse_train_data = np.loadtxt(TRAINING_DATA_FILE, delimiter=' ',dtype=int)


In [4]:
sparse_test_data = np.loadtxt(TEST_DATA_FILE, delimiter=' ',dtype=int )


In [5]:
#Five first rows
sparse_train_data[:5]


array([[ 0,  2,  1,  1],
       [ 0,  3,  1,  2],
       [ 0,  4,  1,  1],
       [ 0,  7,  1,  3],
       [ 0, 11,  1,  1]])

In [6]:
#Five last rows
# documentID -> identify a particular email
# WordID-> identify a particular word
# label -> category 0:non-spam/1: spam
# Occurance -> the number of times this particular words occures
sparse_train_data[-5:]

array([[5795, 2035,    0,    2],
       [5795, 2040,    0,    1],
       [5795, 2272,    0,    1],
       [5795, 2342,    0,    1],
       [5795, 2370,    0,    1]])

In [7]:
print('Nr of rows in training file', sparse_train_data.shape[0])
print('Nr of rows in testing file', sparse_test_data.shape[0])

Nr of rows in training file 258360
Nr of rows in testing file 117776


In [8]:
print('Nr of emails in training file', np.unique(sparse_train_data[:,0]).size)   #select everything in the first column

Nr of emails in training file 4013


In [9]:
print('Nr of emails in test file', np.unique(sparse_test_data[:, 0]).size)

Nr of emails in test file 1724


In [ ]:
#next -> transforming this Numpy array into a pandas's data frame,
# re-structure from sparse matrix to full matrix
# full matrix contained zero values the sparse matrix didnot

### How to Create an empthy DataFrame

- you need to specify what sort of column names

- how many columns you want to have, how many rows you want, what the index names should be
- provide some sort of dummy value for the cells.

- Do you want the cells to be equal to zero or none or one or something else

In [12]:
# third is word id that goes from 0 to 2500 we do it by list
column_names = ['DOC'] + ['CATEGORY'] + list(range(0, VOCAB_SIZE))
column_names[:5]

['DOC', 'CATEGORY', 0, 1, 2]

In [13]:
len(column_names)

2502

In [14]:
index_names = np.unique(sparse_train_data[:,0])
index_names

array([   0,    1,    2, ..., 5791, 5794, 5795])

In [15]:
full_train_data = pd.DataFrame(index=index_names, columns=column_names)

In [16]:
full_train_data.head()

DOC CATEGORY    0    1    2    3    4    5    6    7  ... 2490 2491 2492  \
0  NaN      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN   
1  NaN      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN   
2  NaN      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN   
3  NaN      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN   
4  NaN      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN   

  2493 2494 2495 2496 2497 2498 2499  
0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
4  NaN  NaN  NaN  NaN  NaN  NaN  NaN  

[5 rows x 2502 columns]

In [19]:
# fill the nan with fillna method
full_train_data.fillna(value=0, inplace=True)
full_train_data.head()

DOC  CATEGORY  0  1  2  3  4  5  6  7  ...  2490  2491  2492  2493  2494  \
0    0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0   
1    0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0   
2    0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0   
3    0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0   
4    0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0   

   2495  2496  2497  2498  2499  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     0     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 2502 columns]

# Create a Full Matrix from a Sparse Matrix

In [ ]:
# import the sparse matrix from the txt file
# write a function that creaze a full matrix for us

In [25]:
def make_full_matrix(sparse_matrix, nr_words, doc_idx=0, word_idx=1, cat_idx=2, freq_idx=3):
    """
    Form a full matrix from a sparse matrix. Return a pandas dataframe. 
    Keyword arguments:
    sparse_matrix -- numpy array
    nr_words -- size of the vocabulary. Total number of tokens. 
    doc_idx -- position of the document id in the sparse matrix. Default: 1st column
    word_idx -- position of the word id in the sparse matrix. Default: 2nd column
    cat_idx -- position of the label (spam is 1, nonspam is 0). Default: 3rd column
    freq_idx -- position of occurrence of word in sparse matrix. Default: 4th column
    """
    column_names = ['DOC'] + ['CATEGORY'] + list(range(0, VOCAB_SIZE))
    doc_id_names = np.unique(sparse_matrix[:, 0])
    full_matrix = pd.DataFrame(index=doc_id_names, columns=column_names)
    full_matrix.fillna(value=0, inplace=True)
    
    for i in range(sparse_matrix.shape[0]):
        doc_nr = sparse_matrix[i][doc_idx]
        word_id = sparse_matrix[i][word_idx]
        label = sparse_matrix[i][cat_idx]
        occurrence = sparse_matrix[i][freq_idx]
        
        full_matrix.at[doc_nr, 'DOC'] = doc_nr
        full_matrix.at[doc_nr, 'CATEGORY'] = label
        full_matrix.at[doc_nr, word_id] = occurrence
    
    full_matrix.set_index('DOC', inplace=True)
    return full_matrix

In [26]:
%%time
full_train_data = make_full_matrix(sparse_train_data, VOCAB_SIZE)

CPU times: total: 39.8 s
Wall time: 40 s


In [28]:
full_train_data.tail()

CATEGORY  0  1  2  3  4  5  6  7  8  ...  2490  2491  2492  2493  2494  \
DOC                                        ...                                 
5789         0  3  1  0  1  0  0  0  1  0  ...     0     0     0     0     0   
5790         0  1  1  1  0  0  0  1  0  0  ...     0     0     0     0     0   
5791         0  3  1  0  1  1  0  0  0  1  ...     0     0     0     1     0   
5794         0  1  1  1  0  0  1  2  0  0  ...     0     0     0     0     0   
5795         0  3  4  2  0  5  0  3  0  0  ...     0     0     0     0     0   

      2495  2496  2497  2498  2499  
DOC                                 
5789     0     0     0     0     0  
5790     0     0     0     0     0  
5791     0     0     0     0     0  
5794     0     0     0     0     0  
5795     0     0     0     0     0  

[5 rows x 2501 columns]

# Training the Naive Bayes Model

## Calculating the Probability of Spam

In [ ]:
# Challenge: Calculate the probability of spam - the percent of spam messages in the training
# dataset. Store this value in a variable called prob_spam

In [29]:
# the total number of messages that we have in our data set 
full_train_data.CATEGORY.size

4013

In [30]:
# the number of spam messages
# The reason I can do this is because I've labeled the category of spam as one and the category of non spam at zero.

# So simply summing up all the ones in my category column will give me the number of spam messages of which I've got 1249.


full_train_data.CATEGORY.sum()

1248

In [33]:
prob_spam = full_train_data.CATEGORY.sum() /full_train_data.CATEGORY.size
print('probabaility of spam is : ',prob_spam)

probabaility of spam is :  0.310989284824321


## Total Number of words/Tokens

In [ ]:
# total number of tokens that we have in our dataset
# number of tokens that belong to spam category and nonspam category

In [42]:
# create a subset of our full_train_data --> so just the tokens
# loc is for selecting the number of rows

# just the tokens
full_train_features = full_train_data.loc[:,full_train_data.columns != 'CATEGORY']

In [43]:
full_train_features.head()

0     1     2     3     4     5     6     7     8     9     ...  2490  \
DOC                                                              ...         
0       0     0     1     2     1     0     0     3     0     0  ...     0   
1       7     1     2     0     1     0     0     1     0     0  ...     0   
2       6     1     1     0     1     0     0     1     0     0  ...     0   
3       6     0     0     2     4     0     3    14     0     0  ...     0   
4       5     1     2     0     1     0     0     1     0     0  ...     0   

     2491  2492  2493  2494  2495  2496  2497  2498  2499  
DOC                                                        
0       0     0     0     0     0     0     0     0     0  
1       0     0     0     0     0     0     0     0     0  
2       0     0     0     0     0     0     0     0     0  
3       0     0     0     0     0     0     0     0     0  
4       0     0     0     0     0     0     0     0     0  

[5 rows x 2500 columns]

In [44]:
# Total email length
email_lengths = full_train_features.sum(axis=1) # sum the columns
email_lengths.shape

(4013,)

In [45]:
email_lengths[:5]

C:\Users\tmost\AppData\Local\Temp\ipykernel_11212\2283701581.py:1: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  email_lengths[:5]


DOC
0     87
1     53
2     40
3    183
4     43
dtype: int64

In [47]:
# to get the total number of tokens our total word count -> All we need to do is sum up the values in the entire series.
total_wc = email_lengths.sum()
total_wc

429241

## Number of tokens in Spam and Ham emails

**Challenge** Create a subset of the email_lengths series that only contains the spam messages. Call the subset spam_lengths. Then count the total number of words that occur in spam emails. 

Do the same for the non-spam emails. Create a subset called ham_lengths. Then count the total number of words that occur in the ham emails. 

In [50]:
spam_lengths = email_lengths[full_train_data.CATEGORY == 1]
spam_lengths.shape

(1248,)

In [51]:
spam_wc =spam_lengths.sum()
spam_wc

176334

In [52]:
ham_lengths = email_lengths[full_train_data.CATEGORY == 0]
ham_lengths.shape

(2765,)

In [53]:
nonspam_wc =ham_lengths.sum()
nonspam_wc

252907

In [54]:
# Challenge: Can you figure out if spam emails or non-spam emails tend to be longer? Which
# category contains more tokens? Take a guess and then verify your intuition using the dataset

In [55]:
print('Average nr of words in spam emails {:.0f}'.format(spam_wc / spam_lengths.shape[0])) # float the number
print('Average nr of words in ham emails  {:.3f}'.format(nonspam_wc / ham_lengths.shape[0]))

Average nr of words in spam emails 141
Average nr of words in ham emails 91.467


###  Summing the Tokens Occuring in Spam

In [56]:
full_train_features.shape

(4013, 2500)

In [58]:
train_spam_tokens = full_train_features.loc[full_train_data.CATEGORY == 1]
train_spam_tokens.head()

0     1     2     3     4     5     6     7     8     9     ...  2490  \
DOC                                                              ...         
0       0     0     1     2     1     0     0     3     0     0  ...     0   
1       7     1     2     0     1     0     0     1     0     0  ...     0   
2       6     1     1     0     1     0     0     1     0     0  ...     0   
3       6     0     0     2     4     0     3    14     0     0  ...     0   
4       5     1     2     0     1     0     0     1     0     0  ...     0   

     2491  2492  2493  2494  2495  2496  2497  2498  2499  
DOC                                                        
0       0     0     0     0     0     0     0     0     0  
1       0     0     0     0     0     0     0     0     0  
2       0     0     0     0     0     0     0     0     0  
3       0     0     0     0     0     0     0     0     0  
4       0     0     0     0     0     0     0     0     0  

[5 rows x 2500 columns]

In [59]:
train_spam_tokens.tail()

0     1     2     3     4     5     6     7     8     9     ...  2490  \
DOC                                                               ...         
1885     1     0     0     2     0     1     0     0     0     0  ...     0   
1887     2     0     0     0     0     0     0     0     0     0  ...     0   
1889     0     0     0     0     0     0     0     0     1     0  ...     0   
1890     2     0     0     0     1     0     0     2     0     0  ...     0   
1895     1     1     1     0     0     0     0     0     0     0  ...     0   

      2491  2492  2493  2494  2495  2496  2497  2498  2499  
DOC                                                         
1885     0     0     0     0     0     0     0     0     0  
1887     0     0     0     0     0     0     0     0     0  
1889     0     0     0     0     0     0     0     0     0  
1890     0     0     0     0     0     0     0     0     0  
1895     0     0     0     0     0     0     0     0     0  

[5 rows x 2500 columns]

In [60]:
train_spam_tokens.shape

(1248, 2500)

In [62]:
summed_spam_tokens = train_spam_tokens.sum(axis=0) +1  #+1 is for smoothing technique
summed_spam_tokens.shape

(2500,)

In [63]:
summed_spam_tokens.tail()

2495     2
2496     1
2497    16
2498    14
2499     1
dtype: int64

## Summing the Tokens Occuring in Ham

In [ ]:
# Challenge: Repeat this process for the ham messages. Sum the tokens that occur in the 
# non-spam messages. Store the values in a variable called summed_ham_tokens.

In [64]:
train_ham_tokens = full_train_features.loc[full_train_data.CATEGORY == 0]
summed_ham_tokens = train_ham_tokens.sum(axis=0) +1  #laplace smoothing

In [65]:
summed_ham_tokens.shape

(2500,)

In [66]:
summed_ham_tokens.tail()

2495    27
2496    35
2497    20
2498    15
2499    28
dtype: int64

In [67]:
train_ham_tokens[2499].sum() + 1  # the output should be the same as last entry

28

## P(Token | Spam) - Probability that a Token Occurs given the Email is Spam